# Generated by Django 5.1.3 on 2024-12-03 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='game',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='platform',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='game_list_app.publisher'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='release_date',
            field=models.IntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
