# Generated by Django 5.1.3 on 2024-12-03 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_list_app', '0002_remove_rating_game_remove_rating_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_list_app.publisher'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='release_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
