# Generated by Django 5.1.3 on 2024-12-04 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_list_app', '0003_alter_platform_owner_alter_platform_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='game',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
