# Generated by Django 5.1.3 on 2024-12-04 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_list_app', '0004_game_add_date_game_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='platform',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
