# Generated by Django 5.1.3 on 2024-12-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_list_app', '0007_alter_game_platform_alter_game_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
