# Generated by Django 5.1.3 on 2024-12-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_list_app', '0014_publisher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='platform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
