# Generated by Django 5.1.5 on 2025-02-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_list_app', '0017_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.CharField(choices=[('1/5', 'One'), ('2/5', 'Two'), ('3/5', 'Three'), ('4/5', 'Four'), ('5/5', 'Five')], default='5/5', max_length=10),
        ),
    ]
